spring:
  profiles:
    active: db, core, admin
  messages:
    encoding: UTF-8

server:
  port: 8083

logging:
  level:
    root:  DEBUG #ERROR
    org.springframework:  DEBUG #ERROR
    org.mybatis:  DEBUG #ERROR
    org.linlinjava.litemall.admin:  DEBUG
    org.linlinjava.litemall:  DEBUG #ERROR