spring:
  profiles:
    active: db, core, admin, wx
  messages:
    encoding: UTF-8

server:
  port: 8090

logging:
  level:
    root:  DEBUG #ERROR
    org.springframework:  DEBUG #ERROR
    org.mybatis:  DEBUG #ERROR
    org.linlinjava.litemall.core:  DEBUG #ERROR
    org.linlinjava.litemall.db:  DEBUG #ERROR
    org.linlinjava.litemall.admin:  DEBUG #ERROR
    org.linlinjava.litemall.wx:  DEBUG #ERROR
    org.linlinjava.litemall:  DEBUG #ERROR